# Generated by Django 4.1.4 on 2022-12-17 08:47

import coin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coindatamodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=coin.models.upload_image_path),
        ),
    ]
