# Generated by Django 4.1.4 on 2022-12-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coindatamodel',
            old_name='sybmol',
            new_name='symbol',
        ),
    ]
