# Generated by Django 4.1.4 on 2022-12-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_rename_sybmol_coindatamodel_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coindatamodel',
            name='name',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='coindatamodel',
            name='symbol',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
