# Generated by Django 4.1.4 on 2022-12-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_alter_coindatamodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coindatamodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='path/', verbose_name='img'),
        ),
    ]
