# Generated by Django 4.1.4 on 2023-01-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0003_alter_coindatamodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coindatamodel',
            name='name',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='coindatamodel',
            name='symbol',
            field=models.CharField(max_length=12),
        ),
    ]
